### ISSUE TITLE
Can AXLabel replace AXDescription/AXTitle in core-aam?

### ISSUE THREAD

**Issue by spectranaut** [w3c/core-aam#172]
See: https://w3c.github.io/core-aam/#accessible-names-and-descriptions

Also this would simplify things in chrome.

**Comment by cookiecrook** [comment]
Core-AAM should not require implementations use the newer property, because doing so would cause implementation churn and risk without any additional user benefit. However, to clear the way for implementations wanting to refactor, it is okay to list either. Such as:

- either AXLabel or AXDescription on images
- either AXLabel or AXTitle on buttons
- etc.

**Comment by cookiecrook** [comment]
There was a legacy distinction between visible labels (AXTitle) and invisible labels (AXDescription) in the older ~2003 API that has been determined to be unnecessary. More recent implementations can use AXLabel in either scenario, but AXTitle and AXDescription are not deprecated, so implementations are not required to change.

**Comment by cookiecrook** [comment]
Still thinking about the phrasings. I will edit the above comments and delete this one when it's ready.

**Comment by cookiecrook** [comment]
Core-AAM should not require implementations use `accessibilityLabel`, because doing so 1) may not be feasible in some contexts, and 2) even where it is feasible, would cause implementation churn and risk without any additional user benefit. 

However, there could be mention of the convenience protocol if it would be helpful to implementations. Is it? I don't think adding these will simplify Core-AAM though, if that's your goal.

I'm fairly certain both Chromium and Gecko implementors will want to continue using `accessibilityAttributeValue`, and if so, they should continue using `AXTitle` and `AXDescription`. However, if an implementation were to use the convenience protocol that a SwitftUI/AppKi/UIKit app would use, `accessibilityLabel` would be the preference.

**Comment by cookiecrook** [comment]
@aleventhal @benbeaudry @jcsteh any preference on this?

**Comment by jcsteh** [comment]
We do want to keep using accessibilityAttributeValue. That said, the rules for when to use AXDescription vs AXTitle have caused us a fair bit of trouble, and honestly, I still don't think we quite know precisely when each should be used.

What does accessibilityLabel map to in terms of attributes? Or is it entirely separate? It'd be nice to have a single attribute that is used for all "names".

CC @MReschenberg, who is more familiar with this part of our code.

**Comment by cookiecrook** [comment]
In general, `accessibilityLabel` often maps to `AXDescription`, but there are exceptions. If you file an Apple feedback request for additional documentation of that behavior on behalf of Chromium or Gecko, please send me the feedback ID number. Thanks.

**Comment by cookiecrook** [comment]
I'm sorry, I must've closed this accidentally last week, but if @spectranaut or someone else prefers it be re-opened, by all means. Otherwise, I will leave it closed as I don't recommend this change for the time being.
