### ISSUE TITLE
Add combobox value support for aria#1225

### ISSUE THREAD

**Issue by jnurthen** [w3c/core-aam#76]
Specifically support for
https://github.com/w3c/aria/commit/51ef35c#diff-eacf331f0ffc35d4b482f1d15a887d3bR2136

**Comment by spectranaut** [comment]
It seems like only the "value" calculation of the combobox could be recorded somewhere in CORE-AAM or HTML-AAM. But it doesn't seem obvious to me where in the CORE-AAM we need to reflect these changes, if anywhere. 

Questions:
1. If a text input is given role="combobox", do we expect the "value" attribute of the element to be mapped in anyway differently than `value [ input ]` in [HTML-AAM](https://w3c.github.io/html-aam/)? If so then it seems like we do need to record it somewhere.
2. The `value` of the combobox is expected to be calculated and communicated by the browsers even when the combobox role is on an element that does not already have the concept of a "value". That is clear in the ARIA spec, but does the MAPPING of that value to the accessibility API need to be specified, and if so, where? It seems like this is the mapping of an implicit "value", rather than something specifically set in the html -- so it doesn't belong in [mapping states and properties table](https://w3c.github.io/core-aam/#mapping_state-property_table). But maybe it belongs in the [4.6 Special Processing Requiring Additional Computation](https://w3c.github.io/core-aam/#mapping_additional)

**Comment by spectranaut** [comment]
Thanks for the discussion in the last [meeting](https://www.w3.org/2022/04/07-aria-minutes.html). It was discussed that:
1. There is still work to do in CORE-AAM to better specify value in general, but that does not block this feature
    * Joanie already made an issue for this: https://github.com/w3c/core-aam/issues/70
2. There should be a test case for this particular scenario for ARIA 1.2
    * Joanie already made a test for this: [combobox value calculation](https://github.com/web-platform-tests/wpt/blob/027657d6454e22be38bd2c8145d27633a754b23e/core-aam/combobox-value-calculation-manual.html)
3. textbox and searchbox should also have value calculations.
    * I added an issue: https://github.com/w3c/aria/issues/1720
    
So, I think we can close this issue and consider the feature done :)
